apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # ← don't create new pod before killing old
      maxUnavailable: 1  # ← kill old pod first, then start new
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: cicdtestacr.azurecr.io/django-app:latest
        ports:
        - containerPort: 8000
        env:
          - name: PYTHONDONTWRITEBYTECODE
            value: "1"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: MONGODB_HOST
            value: "mongo-service"
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_NAME
            value: "blogdb"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"