apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer        # gives you a public IP from Azure
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80                # external port (browser)
    targetPort: 8000        # your Django port